### PR TITLE
Update ModularFullRuntime.md

### PR DESCRIPTION
**Pull request by charneykaye**
Implementing this in Gradle 8 this seemed more up to date.

### CODE REVIEW

**Comment by petr-panteleyev** [comment]
I don't want my samples in Groovy, thank you.

**Comment by charneykaye** [comment]
Gradle files ARE groovy, it's just a fact.

**Comment by petr-panteleyev** [comment]
Only if you live in past century. Otherwise it's Kotlin.
Sorry, just kidding. 
Kotlin is my personal preference for gradle. And I actually prefer maven big time.

**Comment by charneykaye** [comment]
🧐 sorry for using your library then

**Pull request closed without merging**
