### PR TITLE
Bump gradle version to 7.4 to support java17

### PR DESCRIPTION
**Pull request by Shoothzj**

### CODE REVIEW

**Comment by petr-panteleyev** [comment]
I'm not sure I understand the purpose of this change. Especially building plugin itself with Java 17.
Do you have any specific issues?

**Comment by Shoothzj** [comment]
> I'm not sure I understand the purpose of this change. Especially building plugin itself with Java 17.
> 
> Do you have any specific issues?

I have a project which using jdk17 gradle7. Use this plugin raised some error. I was wondering update this plugin's gradle version and plugin version can deal with this problem

**Comment by petr-panteleyev** [comment]
That's definitely not related to this plugin.
You may check this branch for example:
https://github.com/petr-panteleyev/password-manager/tree/gradle

**Comment by Shoothzj** [comment]
> That's definitely not related to this plugin.
> 
> You may check this branch for example:
> 
> https://github.com/petr-panteleyev/password-manager/tree/gradle
> 
> 

Thank you. Let me figure out why.

**Pull request closed without merging**
